import argparse

def get_parameters():
    parser = argparse.ArgumentParser()
    parser.add_argument('--flow_path_BJ', type=str,
                        default='../data/long_data/BJ/grid_bj_flow.txt')
    parser.add_argument('--static_adj', type=str, default='../data/long_data/BJ/adj_grid_beijing.txt')
    parser.add_argument('--BJ_POI', type=str, default='../data/long_data/BJ/poi_bd.npy')
    parser.add_argument('--data', type=str, default='BJ')
    parser.add_argument('--data_type', type=str, default='4D')
    parser.add_argument('--x_offsets', type=int, default=14)
    parser.add_argument('--y_offsets', type=int, default=14)
    parser.add_argument('--y_start', type=int, default=1)
    parser.add_argument('--device', type=str, default='cuda:0')
    parser.add_argument('--input_dim', type=int, default=24)
    parser.add_argument('--hidden_dim_high', type=int, default=64)
    parser.add_argument('--hidden_dim_low', type=int, default=64)
    parser.add_argument('--out_dim', type=int, default=24)
    parser.add_argument('--gcn_depth', type=int, default=2)
    parser.add_argument('--node_num', type=int, default=185)
    parser.add_argument('--his_ts', type=int, default=14)
    parser.add_argument('--dropout', type=float, default=0.5)
    parser.add_argument('--dropout_type', type=str, default='zoneout')
    parser.add_argument('--pre_ts', type=int, default=14)
    parser.add_argument('--pre_num', type=int, default=1, help='predict pre_num ts in a day')
    parser.add_argument('--output', type=int, default=1)
    parser.add_argument('--node_embed_dim', type=int, default=5)
    parser.add_argument('--depth', type=int, default=10)
    parser.add_argument('--batch', type=int, default=32)
    parser.add_argument('--logger_dir', type=str, default='../experiments/BJ')
    parser.add_argument('--lr', type=float, default=0.001)
    parser.add_argument('--weight_decay', type=float, default=0.0001)
    parser.add_argument('--milestones', type=list, default=[10, 20, 40, 60])
    parser.add_argument('--lr_decay_ratio', type=float, default=0.8)
    parser.add_argument('--loss_type', type=str, default='Smooth')
    parser.add_argument('--max_grad_norm', type=int, default=5)
    parser.add_argument('--min_lr', type=float, default=2.0e-06)
    parser.add_argument('--epochs', type=int, default=100)
    parser.add_argument('--model_name', type=str, default='DeCau')
    parser.add_argument('--save_path_ckpt', type=str, default='../ckpt/BJ')
    parser.add_argument('--adj_type', type=str, default='asym_adj')
    parser.add_argument('--dynGraphGenerate_norm', type=str, default='D-1')
    parser.add_argument('--is_test', type=bool, default=True)
    parser.add_argument('--gso_type', type=str, default='sym_norm_lap',
                        choices=['sym_norm_lap', 'rw_norm_lap', 'sym_renorm_adj', 'rw_renorm_adj'])
    parser.add_argument('--patience', type=int, default=7, help='early stopping patience')
    parser.add_argument('--beta', type=float, default=0.5)
    parser.add_argument('--K', type=int, default=4, help='the history length of POI, overlap 1 month')
    parser.add_argument('--train_ratio', type=float, default=0.7)
    parser.add_argument('--val_ratio', type=float, default=0.2)
    parser.add_argument('--num_layer', type=int, default=1)
    parser.add_argument('--num_context', type=int, default=7)
    parser.add_argument('--num_pseudo', type=int, default=185 * 2)
    parser.add_argument('--kl_ratio', type=float, default=1)
    parser.add_argument('--Kt', type=int, default=3)
    parser.add_argument('--stblock_num', type=int, default=2)
    parser.add_argument('--decomp_kernel', type=int, default=24)

    args = parser.parse_args()

    return args